### ISSUE TITLE
Add `name` field to asset info

### ISSUE THREAD

**Issue by nosovk** [thgh/rollup-plugin-css-only#26]
Issue connected to https://github.com/shuizhongyueming/rollup-plugin-output-manifest/issues/6

Current version does not emit `name` for assets
https://github.com/thgh/rollup-plugin-css-only/blob/master/src/index.js#L80

which causes absence of generated css files in resulting manifest.

Probably it would correct to put `filename` into `name` property?

**Comment by thgh** [comment]
When using name instead of filename, then the final filename is `[name]-[hash].css` by default, but that's different from the classic behaviour, so I used filename instead. It would be useful if someone could research how other plugins handle this.

**Comment by RianFuro** [comment]
I just needed to research other plugins for a different issue and stumbled across this. The 2 alternative css bundler plugins are split on that issue as well:

- [egoist/rollup-plugin-postcss](https://github.com/egoist/rollup-plugin-postcss) emits with a filename: https://github.com/egoist/rollup-plugin-postcss/blob/master/src/index.js#L244-L255
- [Anidetrix/rollup-plugin-styles](https://github.com/Anidetrix/rollup-plugin-styles) emits with a name: https://github.com/Anidetrix/rollup-plugin-styles/blob/master/src/index.ts#L288-L289 (They made the change here, on a major version bump: https://github.com/Anidetrix/rollup-plugin-styles/commit/c0a7daa767ccb94e06ea1509e3cc012fca4ae2d9#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80)

Personally, while I don't currently need this resolved, I know that appending a content hash to a bundle is a good way to deal with browser cache invalidation. So, since the generated filename can be controlled by the [`outputs.assetFileNames`](https://rollupjs.org/guide/en/#outputassetfilenames) property if the hash is not needed, I would prefer using `name` since it's more flexible.

**Comment by thgh** [comment]
Let's make them separate options in v4.1.0
